target "Cliplay_new" do
pod 'DGActivityIndicatorView'
pod 'CNPPopupController'
pod 'UITableView+FDTemplateLayoutCell'
pod 'TTTAttributedLabel'
pod 'LoopBack', :git => 'https://github.com/strongloop/loopback-sdk-ios.git'
pod 'JTTableViewController', '~> 1.0'
pod 'WeiboSDK', :git => 'https://github.com/sinaweibosdk/weibo_ios_sdk.git'
pod 'YYImage/WebP'
pod 'YYWebImage'
pod 'FontAwesomeKit/FontAwesome'
pod 'FontAwesomeKit/IonIcons'
pod 'MRProgress'
pod 'UINavigationItem+Margin'
pod 'FCUUID'
pod 'AppSettings'
pod 'STPopup'
pod 'LKBadgeView', :git => 'https://github.com/lakesoft/LKBadgeView.git'
pod 'JDStatusBarNotification'
pod 'TLYShyNavBar'
pod 'KMNavigationBarTransition'
#pod 'ASValueTrackingSlider'
#pod 'JDFPeekaboo'
#pod 'couchbase-lite-ios'
#pod 'JGActionSheet'
#pod 'Fingertips'
#pod 'REComposeViewController', '~> 2.3.2'
end
